name: build
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - uses: actions/checkout@v2

    - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.33.0
    - run: golangci-lint run  
    
    - run: go test -v ./...
    - run: go build -v ./...
